-- Minimal ORDS example: service tickets.
-- Two tables, enough rows to exercise paging. Run as your ORDS-enabled schema.

CREATE TABLE tickets (
  id             NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  reference      VARCHAR2(20)  NOT NULL UNIQUE,
  subject        VARCHAR2(200) NOT NULL,
  status         VARCHAR2(20)  NOT NULL,     -- OPEN | IN_PROGRESS | RESOLVED
  priority       VARCHAR2(10)  NOT NULL,     -- LOW | MEDIUM | HIGH
  queue_id       NUMBER        NOT NULL,
  assigned_to    VARCHAR2(60),
  created_date   TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE TABLE queues (
  id    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code  VARCHAR2(20)  NOT NULL UNIQUE,
  name  VARCHAR2(100) NOT NULL
);

ALTER TABLE tickets ADD CONSTRAINT fk_tickets_queue
  FOREIGN KEY (queue_id) REFERENCES queues (id);

INSERT INTO queues (code, name) VALUES ('NETWORK',  'Network Operations');
INSERT INTO queues (code, name) VALUES ('HARDWARE', 'Hardware Support');
INSERT INTO queues (code, name) VALUES ('ACCESS',   'Access Management');

INSERT INTO tickets (reference, subject, status, priority, queue_id, assigned_to)
VALUES ('TKT-1001', 'VPN drops every few minutes', 'OPEN', 'HIGH', 1, NULL);
INSERT INTO tickets (reference, subject, status, priority, queue_id, assigned_to)
VALUES ('TKT-1002', 'Laptop will not charge', 'IN_PROGRESS', 'MEDIUM', 2, 'j.rivera');
INSERT INTO tickets (reference, subject, status, priority, queue_id, assigned_to)
VALUES ('TKT-1003', 'Cannot access shared drive', 'OPEN', 'LOW', 3, NULL);
INSERT INTO tickets (reference, subject, status, priority, queue_id, assigned_to)
VALUES ('TKT-1004', 'Switch port flapping in rack 4', 'OPEN', 'HIGH', 1, 'p.osei');
INSERT INTO tickets (reference, subject, status, priority, queue_id, assigned_to)
VALUES ('TKT-1005', 'Monitor flickers on dock', 'RESOLVED', 'LOW', 2, 'j.rivera');
COMMIT;
